output_features = {
    "prevalence_CA_state_total_Latent": "The total number of individuals in California who are currently infected but not yet infectious. These individuals have contracted the disease but are in the incubation period, where they cannot transmit the virus to others.",
    "prevalence_CA_state_total_Infectious_symptomatic": "The total count of individuals in California who are currently infectious and showing symptoms of the disease. These people are capable of transmitting the virus and are exhibiting noticeable signs of infection.",
    "prevalence_CA_state_total_Infectious_asymptomatic": "The total number of people in California who are currently infectious but not showing any symptoms. Despite appearing healthy, these individuals can still spread the virus, making them particularly important in disease transmission dynamics.",
    "prevalence_CA_state_total_Hospitalized": "The total count of individuals in California who are currently hospitalized due to the disease. This includes all patients requiring hospital care, excluding those in intensive care units.",
    "prevalence_CA_state_total_ICU": "The total number of patients in California currently receiving care in Intensive Care Units (ICUs) due to severe complications of the disease. These represent the most critical cases requiring advanced medical intervention.",
    "prevalence_CA_state_total_Removed_asymptomatic": "The cumulative count of individuals in California who have recovered from asymptomatic infections. These people were infected and infectious without showing symptoms and have now cleared the virus.",
    "prevalence_CA_state_total_Removed_symptomatic": "The total number of people in California who have recovered from symptomatic infections. These individuals experienced noticeable symptoms, have overcome the disease, and are no longer infectious.",
    "prevalence_CA_state_total_Home_asymptomatic": "The current count of individuals in California who are infected, asymptomatic, and managing their condition at home. These people may be unaware of their infection but are potentially spreading the virus.",
    "prevalence_CA_state_total_Home_mild": "The total number of people in California with mild symptoms who are currently managing their illness at home. These individuals have noticeable but not severe symptoms and do not require hospitalization.",
    "prevalence_CA_state_total_Home_severe": "The count of individuals in California with severe symptoms who are currently managing their condition at home. This may include people awaiting hospital admission or those who choose to remain at home despite severe symptoms.",
    "prevalence_CA_state_total_Removed_hospitalized": "The cumulative number of people in California who were hospitalized due to the disease and have now recovered. This represents those who required hospital care but have since been discharged and are no longer infectious.",
    "prevalence_CA_state_total_Deaths_hospitalized": "The total number of deaths in California among patients who were hospitalized due to the disease. This represents fatalities that occurred in a hospital setting.",
    "incidence_CA_state_total_Latent": "The number of new latent infections in California over a specific time period. This represents individuals who have newly contracted the disease but are not yet infectious or showing symptoms.",
    "incidence_CA_state_total_Infectious_symptomatic": "The count of new cases in California that have become infectious and symptomatic over a given time period. These are newly identified cases where individuals are capable of spreading the virus and showing signs of infection.",
    "incidence_CA_state_total_Infectious_asymptomatic": "The number of new cases in California that have become infectious but remain asymptomatic over a specific time frame. These individuals can spread the virus despite not showing any symptoms.",
    "incidence_CA_state_total_Hospitalized": "The count of new hospital admissions in California due to the disease over a given period. This represents the influx of patients requiring hospital care, indicating the current burden on the healthcare system.",
    "incidence_CA_state_total_ICU": "The number of new admissions to Intensive Care Units in California over a specific time period. This indicates the rate at which severe cases are emerging, requiring critical care.",
    "incidence_CA_state_total_Removed_asymptomatic": "The count of new recoveries in California among asymptomatic cases over a given time frame. This represents individuals who were unknowingly infected and have now cleared the virus.",
    "incidence_CA_state_total_Removed_symptomatic": "The number of new recoveries in California among symptomatic cases over a specific period. This indicates how many people have overcome noticeable infections and are no longer infectious.",
    "incidence_CA_state_total_Home_asymptomatic": "The count of new asymptomatic cases in California managing their condition at home over a given time period. These are newly identified cases where individuals are infected but not showing symptoms.",
    "incidence_CA_state_total_Home_mild": "The number of new mild cases in California managing their illness at home over a specific time frame. This represents the influx of cases with noticeable but not severe symptoms.",
    "incidence_CA_state_total_Home_severe": "The count of new severe cases in California managing their condition at home over a given period. This may include people waiting for hospital admission or choosing to stay home despite severe symptoms.",
    "incidence_CA_state_total_Removed_hospitalized": "The number of new recoveries in California among previously hospitalized patients over a specific time period. This represents recently discharged patients who have overcome the disease.",
    "incidence_CA_state_total_Deaths_hospitalized": "The count of new deaths in California among hospitalized patients over a given time frame. This represents recent fatalities that occurred in a hospital setting due to the disease.",
}

input_features = {
    "seasonality_min": "The minimum seasonal effect on disease transmission. This parameter captures the lowest point of seasonal variation in disease spread, typically observed during warmer months for respiratory diseases. It reflects how environmental factors like temperature, humidity, and human behavior patterns influence the disease's transmission rate throughout the year.",
    "omega_community_interventions": "The effectiveness of interventions implemented in community settings. This parameter quantifies the impact of measures such as mask mandates, social distancing rules, and limitations on public gatherings. It represents how well these community-level interventions reduce disease transmission in public spaces, events, and general community interactions.",
    "omega_work_interventions": "The effectiveness of interventions in work environments. This measure assesses the impact of workplace policies like remote work arrangements, physical distancing in offices, improved ventilation, and hygiene practices. It indicates how successfully these interventions reduce disease spread in various professional settings.",
    "omega_school_interventions": "The effectiveness of interventions implemented in school settings. This parameter evaluates the impact of measures such as hybrid or online learning models, classroom distancing, mask requirements, and enhanced cleaning protocols in educational institutions. It reflects how well these interventions mitigate disease transmission among students, teachers, and staff.",
    "omega_home_interventions": "The effectiveness of interventions in home settings. This measure quantifies the impact of guidelines and policies targeting household transmission, such as isolation protocols for infected individuals, hygiene recommendations, and advice on managing visitors. It represents the success of efforts to reduce disease spread within family units and shared living spaces.",
    "alpha_school_interventions": "The rate or level of adherence to school interventions. Unlike the omega parameter which measures effectiveness, alpha focuses on how consistently and thoroughly school-based interventions are implemented and followed. This could include factors like compliance with mask-wearing, adherence to distancing guidelines, and participation in testing programs.",
    "transit_commute_interventions": "The measures implemented to reduce disease spread in public transportation and during commutes. This parameter assesses the effectiveness of interventions such as capacity limits on public transport, increased sanitation, mask requirements, and altered schedules to reduce crowding. It reflects how well these measures mitigate transmission risks associated with daily travel and commuting.",
    "international_travel_interventions": "The policies and actions implemented to manage disease spread through international travel. This measure evaluates the effectiveness of interventions like travel restrictions, quarantine requirements for international arrivals, pre-travel testing policies, and enhanced screening at ports of entry. It indicates how successfully these measures prevent or reduce the importation of cases from other countries.",
    "domestic_travel_interventions": "The policies and actions implemented to manage disease spread through domestic travel. Similar to international interventions, this parameter assesses measures applied to travel within the country, such as interstate travel restrictions, health screenings at domestic airports, and guidelines for travelers. It reflects the effectiveness of efforts to limit disease spread between different regions or states.",
    "R0": "The basic reproduction number of the disease, representing the average number of secondary infections caused by one infected individual in a completely susceptible population. This fundamental epidemiological parameter indicates the disease's inherent transmissibility in the absence of any control measures or immunity. A higher R0 suggests a more contagious disease that spreads more easily through the population.",
}

counties = [
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Orange",
    "Placer",
    "Plumas",
    "Riverside",
    "Sacramento",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Joaquin",
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Ventura",
    "Yolo",
    "Yuba",
]
